# Generated by Django 5.1.2 on 2024-11-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('processing', 'processing'), ('fulfilled', 'fulfilled'), ('cancelled', 'cancelled'), ('shipped', 'shipped'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paypal', 'paypal'), ('Strip', 'Strip'), ('PayU', 'PayU'), ('Razorpay', 'Razorpay')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('processing', 'processing'), ('paid', 'paid'), ('failed', 'failed')], default='processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('processing', 'processing'), ('fulfilled', 'fulfilled'), ('cancelled', 'cancelled'), ('shipped', 'shipped'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shipping_service',
            field=models.CharField(blank=True, choices=[('Fedx', 'fedx'), ('UPS', 'UPS'), ('DHL', 'DHL')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('disabled', 'disabled'), ('draft', 'draft'), ('published', 'published')], default='published', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, '★★★★★'), (2, '★★☆☆☆'), (4, '★★★★☆'), (1, '★☆☆☆☆'), (3, '★★★☆☆')], default=None),
        ),
    ]
