# Generated by Django 5.1.2 on 2024-11-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('New order', 'New order'), ('Item Delivered', 'Item Delivered'), ('Item Shipped', 'Item Shipped')], default=None, max_length=100),
        ),
    ]
